# Generated by Django 5.1.4 on 2025-01-09 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('street', models.CharField(max_length=50)),
                ('building_num', models.CharField(max_length=7)),
                ('korp', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True)),
                ('sort_num', models.IntegerField()),
            ],
            options={
                'ordering': ['sort_num'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('number_of_floors', models.CharField(max_length=10)),
                ('number_of_entrances', models.IntegerField()),
                ('number_of_elevators', models.IntegerField()),
                ('number_of_chutes', models.IntegerField()),
                ('number_of_residents', models.IntegerField()),
                ('cleaning_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residential_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specifications.address')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=5)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='specifications.building')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='building_expenses', to='specifications.expenseitem')),
            ],
        ),
    ]
