# Generated by Django 5.1.4 on 2025-01-05 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(unique=True)),
                ('street', models.CharField(max_length=50)),
                ('building_num', models.CharField(max_length=7)),
                ('korp', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('number_of_floors', models.CharField(max_length=10)),
                ('number_of_elevators', models.IntegerField()),
                ('number_of_chutes', models.IntegerField()),
                ('number_of_residents', models.IntegerField()),
                ('number_of_entrances', models.IntegerField()),
                ('cleaning_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('residential_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='specifications.address')),
            ],
        ),
    ]
