# Generated by Django 5.1.4 on 2025-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_expenses_summ_alter_address_korp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='sort_num',
            field=models.IntegerField(default=0),
        ),
    ]
