# Generated by Django 5.1.4 on 2025-01-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0003_expenseitem_content_alter_expenseitem_sort_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='specifications.address'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.CharField(default='месяц', max_length=5),
        ),
    ]
