# Generated by Django 5.1.4 on 2025-01-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0004_alter_building_address_alter_expenses_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
    ]
