"""Initial migrations

Revision ID: 7bccf0443871
Revises: 
Create Date: 2025-01-14 16:15:07.909422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bccf0443871'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specifications_building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('number_of_floors', sa.Integer(), nullable=True),
    sa.Column('number_of_entrances', sa.Integer(), nullable=True),
    sa.Column('number_of_elevators', sa.Integer(), nullable=True),
    sa.Column('number_of_chutes', sa.Integer(), nullable=True),
    sa.Column('number_of_residents', sa.Integer(), nullable=True),
    sa.Column('cleaning_area', sa.Float(), nullable=True),
    sa.Column('residential_area', sa.Float(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specifications_building_id'), 'specifications_building', ['id'], unique=False)
    op.create_index(op.f('ix_specifications_building_slug'), 'specifications_building', ['slug'], unique=True)
    op.create_index(op.f('ix_specifications_building_title'), 'specifications_building', ['title'], unique=False)
    op.create_table('specifications_expenseitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sort_num', sa.Integer(), autoincrement=True, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_specifications_expenseitem_id'), 'specifications_expenseitem', ['id'], unique=False)
    op.create_index(op.f('ix_specifications_expenseitem_slug'), 'specifications_expenseitem', ['slug'], unique=True)
    op.create_index(op.f('ix_specifications_expenseitem_sort_num'), 'specifications_expenseitem', ['sort_num'], unique=False)
    op.create_table('specifications_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('summ', sa.Float(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['specifications_building.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['specifications_expenseitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specifications_expenses_id'), 'specifications_expenses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specifications_expenses_id'), table_name='specifications_expenses')
    op.drop_table('specifications_expenses')
    op.drop_index(op.f('ix_specifications_expenseitem_sort_num'), table_name='specifications_expenseitem')
    op.drop_index(op.f('ix_specifications_expenseitem_slug'), table_name='specifications_expenseitem')
    op.drop_index(op.f('ix_specifications_expenseitem_id'), table_name='specifications_expenseitem')
    op.drop_table('specifications_expenseitem')
    op.drop_index(op.f('ix_specifications_building_title'), table_name='specifications_building')
    op.drop_index(op.f('ix_specifications_building_slug'), table_name='specifications_building')
    op.drop_index(op.f('ix_specifications_building_id'), table_name='specifications_building')
    op.drop_table('specifications_building')
    # ### end Alembic commands ###
